import type { Metadata } from "next";
import { ThemeProvider } from "@/components/layout/theme-provider";
import "./globals.css";
import {Navbar} from "../components/layout/Navbar"
import {Inter} from "next/font/google";
import {cn} from "../lib/utils";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={cn("min-h-screen bg-background", inter.className)}
      >
        <ThemeProvider attribute="class"
        defaultTheme="system"
        >
          <Navbar />
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
